# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: beta-xcode6.1

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=34
    - CONDA_PY=35
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "axlqi3dcjSYcZpoLZVL0vgNaw5mBzOBNOaa52qe4C50bEMzfzOLg6y57do3+aRYEBVfOpF5x3T+Wl15/jIcy0lblXH3hAw9a9S/9v1lBzfddhG6A8Ac8Ud2CJA4QsbDmcU3VjOmX3ZVKLsXJONKPQz6+Z/QP029OkLUBQTP6YtP0ZwiF2Zes9M+wfVXAd1pStvcz6i0hVOBOISKaz0dwAqN3YJYIEgpNl/HEgn0/zCZna3qhXs50Kkj+K3XbdLT/SppsKa5KxtxHNlCpWwfcxGXPePsvfPbgD//cR+xUHsnLa9+AQ2HZKnRNgt+bIfpsW4PpWHJ7OYMOMvEpZ6HF0AGOiabuwuLnpTJ+9YsIYq9mazKlDxU1KYLldS+5aH3FDmAyWsvZmyES9voFNuBIaCv3Ri3EpQgQM0YMe9j71M/fVVleI2vQSFca6xRGApH1RYWAMofCSulj47bhBkUYzxJCzB0MqkkfGi58PY/POs0barYfrIfW2LJIEUdDRInYNJUtEnecOcNJm9jio0CMdL3VJPqYA2tofuUT7ZkKB9I5RGC3ZMqlDudSzChBalvIMgeYhf0OsbPHHKo4RzFEFLdrMxBWRNb8qUxdgfpk2Jeb/ZiwgK0CyP9aOmJ8TnFfskUigCf2HoNrxTSbVwP/zvwGWh7xMu289/tiMwUmmDU="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      source /Users/travis/miniconda3/bin/activate root
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
