travis:
  secure:
    BINSTAR_TOKEN: Ik9g9Zows8KQMwGeXOCCVML99qiqcvJQL+YHEQkouBspF5ikD8ml4whjyQjz2QWhUhQlxNvY/jcNLf9vHVRAyGnF1QWkezE9ngiVF3MS92AwfmHhsZcow8P+6Pg+7tfkZZ4yZ7G4zHDQtyahT/HYdABmshiuhfL2Eg8LwzhyWMnoYFgmbeIggE6pbNKn2Ggk7wKRhIxcFCEo6P99bJo1E39MdgHyAwBA0GyNEfS5VBtNP5gNH3HNgA5JEv3VePzIIEgQ7eDKJ4QL4gMpQzd4Lo0f3IXlzTO9+gpA+oUPoO1FKT8fE+vWGeSlFxAMxaGkOz6epSwAVpN25sQA5LOlABwIlG08Di3ZW0SjLoHOP3Z+qzHm7yLlTk3y/EyGtpPyKhAi55yJ1CVe1eKes47Zq/dbsmlib7AMH1vqApBvNzBupb+GY5OaNRg4rAx2lRRHBUDwaT7BIpq7m/ReV86mcZ01NCMkM5yCD3nd7+wrOiiB+EY1dAuLBbrAZcEeEukcJTZzuL4jylfIB/MJvJTqCQU312z4REVqEvPvBK5mBUR/vBtDyd38tVbzVgfD4rMFBg5TZ5TE9rJ+tegEXU5rUPdNqxLI7kSD+6iQP+xSiZawn2ZGmqf3S3Pg1TOSxaBzaGeIJTNsQmcO3kv84ofTAmVtDaK80IOB/9A8X2w+tRM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
