travis:
  secure:
    BINSTAR_TOKEN: a6Q46N7m/nS8iMcKqwOUZJ1+mJCYyELb9nqEGkU2jA1Li7vq2XwkBQrT8CUhf0+sHWanvAT4/qTF94y/gx404MWaZAkKKrt6o3qAS8KlVsMFWTnanKO26AFbQxaMqcZ2q4n/NFBsOs1VCtro9/rOhL/0oPIxEMPJcgfiWGZuPZRwtwRTPSYjV+zAqdLcEWloMQjZaLp8MmJOSohfOhZHC34LYtFqRzuDJXtlcTmHJDVwQnJt1SlkLBracn8FCXxL0hxxgYgRVzuntlyRAkFhaeS0q0iRMhRcJw4VUi2rDwF2VnBnrdfvxtA6cKJV6ti2r6NXte5mRlmKZ6f+C0QP5eQiBQB7Rudeqnt6P4bNEzWVno2MbFS1H/avy/7MDMdvynQoVWWg1IwiHDEp/3GXBLouv+WnkTnl5KBG8ysn77NZStrFoLJUeD6zkatPCbNIDZXS97KRi1wACIt+3tAgXiYy+61/PtR1xfYqWGyoL+unCEkkyFZjyQTxVopb939Wk2KGeVn7RN0jd99J1PK+bfE+dwFh9Qv50HwGB6MmTy6F3cQhaEmIrv5yPcdgj2sDeljFPWvtuu3kTr3HDuO5rrV+xaO6kgWj0kEDtOrz8nNsEO9VYjCme1HY6zhQLU1GmM3BV7Pfm7puBFUo8Zvf5qXLKBXZwW97dVKdQwc2cOk=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
