travis:
  secure:
    BINSTAR_TOKEN: dauVjmAkbxezktEAITUUgGJmNPXOXbk8BfXSPEf4anqNWVtGpamL8A1WtfmY7HD1rCuMoYn6b5zhNduq0fA3X4PQfsfKISE+WBq6A4CRJg5Z5FSU2S6IbOI4r3gVng+tvs1YJJT+lU+94HSaKLuppMoXUVV/ZD3s6WAD0USh5z5pq9TF+COKU3Ao8f5/KAUeqN49bnrmmREoq3bFQrZ3I3XjiHQJzOyLWaX/XGzoSyTjtyf+J3vsE8I4ZEGNatzLOsa2aEj0lNF8mGEa2nD/DLKMGbJS0FwBWo2pDt/4qDE2ZDbxuFFQwf10QOzcXd9ruqk2+gO6X2g9NwzaWN5uBfEdmLTZpVYdIxH4xPd/S64ZRdjffScE+QTarDS3krnM8Lp3CbNMcyWfgwRViv6v3Cuymw5Vrf5sYz6ZGkjX76zEqCGq7vazdxru+05HnyjJwba9dgXa5JnDyYs0N1AXiXLwtfksm0zDtNR7ZIvT/4qXitlCAFih7zLMqIucoVuQT7HBCTLSxFt1A6ZMcZ9khLQMR0l8xTlHgZUz4WMFvMflwLbuUGSWgOIbGtItOlRgpellfvM9YtFNdcW/PcwITqigt9mAlXQvIKCi2vpuJHu/e33a68O6BCjQvA+Ut/j5S/dzzRg7MYi4+8wcRK6lrb9HGz5o4VkPwzEvc8OBGCo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
